ifeq ($(.CURDIR),)
	current_dir  = $(shell /bin/pwd)
else
	current_dir  = $(.CURDIR)
endif

GO          ?= go
GOOS 		?= $(shell $(GO) env GOOS)
GOARCH 		?= $(shell $(GO) env GOARCH)
TOOLBIN 	 = $(.CURDIR)/toolbin/$(GOOS)_$(GOARCH)

.DEFAULT: build

.PHONY: build
build: generate
	./scripts/gofmt

.PHONY: generate
generate: testvecs_test.go

.PHONY: x
x:
	echo THING is $(current_dir)

testvecs_test.go: build-tools/mk-test-vectors
	$(GO) generate common_test.go

PKGS = $(shell $(GO) list ./... | egrep -v '/examples/|/build-tools/')

.PHONY: test
test: $(TOOLBIN)/gocovmerge $(TOOLBIN)/go-test-coverage
	@echo "==> check code formatting"
	@./scripts/gofmt
	@echo "==> run tests for " $(PKGS)
	@${GO} test $(PKGS) -coverprofile=cover.out -covermode=atomic
	@go tool cover -html=cover.out -o coverage.html
	@$(TOOLBIN)/go-test-coverage --config .testcoverage.yml

.PHONY: lint
lint: | $(TOOLBIN)/golangci-lint
	$(TOOLBIN)/golangci-lint run 

.PHONY: tools
tools: $(TOOLBIN)/golangci-lint $(TOOLBIN)/gocovmerge $(TOOLBIN)/go-test-coverage
	@echo "==> installing required tooling..."

$(TOOLBIN)/golangci-lint:
	GOBIN=$(TOOLBIN) GO111MODULE=on $(GO) install github.com/golangci/golangci-lint/cmd/golangci-lint@v1

$(TOOLBIN)/gocovmerge:
	GOBIN=$(TOOLBIN) GO111MODULE=on $(GO) install github.com/wadey/gocovmerge@latest

$(TOOLBIN)/go-test-coverage:
	GOBIN=$(TOOLBIN) GO111MODULE=on $(GO) install github.com/vladopajic/go-test-coverage/v2@latest

.PHONY: gdb
gdb:
	GO_CFLAGS="-g" $(GO) test -c  -timeout 30s
	gdb ./go-gssapi-c.test
